GAME_STATUS_MAPMODE = 1
GAME_STATUS_FIGHTMODE = 2
GAME_STATUS_QUESTMODE = 3
GAME_STATUS_DIALOGMODE = 4

MAP_DIRECTION_UP = 1
MAP_DIRECTION_DOWN = 3
MAP_DIRECTION_LEFT = 4
MAP_DIRECTION_RIGHT = 2

MAP_LOCKED = 1
MAP_UNLOCKED = 0

LOCK = 1
UNLOCK = 0